services:
  postgres:
    build:
      context: ./postgres/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    image: postgres
    ports:
      - 5432:5432
    restart: always
  api:
    build:
      context: ./api/
    depends_on:
      - postgres
    environment:
      API_MODE: ${API_MODE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${API_PORT}:3000
  website:
    build:
      args:
        API_URL: ${API_URL}
      context: ./website/
    depends_on:
      - api
    ports:
      - ${WEBSITE_PORT}:3000
